/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelsRouteRouteImport } from './routes/models/route'
import { Route as ModelsLocalRouteImport } from './routes/models/local'
import { Route as ModelsCommunityRouteImport } from './routes/models/community'
import { Route as EditModelIdRouteImport } from './routes/edit.$modelId'

const ModelsRouteRoute = ModelsRouteRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => rootRouteImport,
} as any)
const ModelsLocalRoute = ModelsLocalRouteImport.update({
    id: '/local',
    path: '/local',
    getParentRoute: () => ModelsRouteRoute,
} as any)
const ModelsCommunityRoute = ModelsCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => ModelsRouteRoute,
} as any)
const EditModelIdRoute = EditModelIdRouteImport.update({
    id: '/edit/$modelId',
    path: '/edit/$modelId',
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    '/models': typeof ModelsRouteRouteWithChildren
    '/edit/$modelId': typeof EditModelIdRoute
    '/models/community': typeof ModelsCommunityRoute
    '/models/local': typeof ModelsLocalRoute
}
export interface FileRoutesByTo {
    '/models': typeof ModelsRouteRouteWithChildren
    '/edit/$modelId': typeof EditModelIdRoute
    '/models/community': typeof ModelsCommunityRoute
    '/models/local': typeof ModelsLocalRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/models': typeof ModelsRouteRouteWithChildren
    '/edit/$modelId': typeof EditModelIdRoute
    '/models/community': typeof ModelsCommunityRoute
    '/models/local': typeof ModelsLocalRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
        | '/models'
        | '/edit/$modelId'
        | '/models/community'
        | '/models/local'
    fileRoutesByTo: FileRoutesByTo
    to: '/models' | '/edit/$modelId' | '/models/community' | '/models/local'
    id:
        | '__root__'
        | '/models'
        | '/edit/$modelId'
        | '/models/community'
        | '/models/local'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    ModelsRouteRoute: typeof ModelsRouteRouteWithChildren
    EditModelIdRoute: typeof EditModelIdRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/models': {
            id: '/models'
            path: '/models'
            fullPath: '/models'
            preLoaderRoute: typeof ModelsRouteRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/models/local': {
            id: '/models/local'
            path: '/local'
            fullPath: '/models/local'
            preLoaderRoute: typeof ModelsLocalRouteImport
            parentRoute: typeof ModelsRouteRoute
        }
        '/models/community': {
            id: '/models/community'
            path: '/community'
            fullPath: '/models/community'
            preLoaderRoute: typeof ModelsCommunityRouteImport
            parentRoute: typeof ModelsRouteRoute
        }
        '/edit/$modelId': {
            id: '/edit/$modelId'
            path: '/edit/$modelId'
            fullPath: '/edit/$modelId'
            preLoaderRoute: typeof EditModelIdRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

interface ModelsRouteRouteChildren {
    ModelsCommunityRoute: typeof ModelsCommunityRoute
    ModelsLocalRoute: typeof ModelsLocalRoute
}

const ModelsRouteRouteChildren: ModelsRouteRouteChildren = {
    ModelsCommunityRoute: ModelsCommunityRoute,
    ModelsLocalRoute: ModelsLocalRoute,
}

const ModelsRouteRouteWithChildren = ModelsRouteRoute._addFileChildren(
    ModelsRouteRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
    ModelsRouteRoute: ModelsRouteRouteWithChildren,
    EditModelIdRoute: EditModelIdRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
